version: '3.3'

# Create a persistent volume across services
volumes:
  builds: {}

services:
  # Base builder image
  builder:
    image: builder:${TAG}_Qt${QT_VERSION}
    build:
      context: .
      dockerfile: dockerHelper/builders/${TAG}/Dockerfile
      args:
        - QT_VERSION=${QT_VERSION}

  # CMake configure service
  gen_cmake:
    image: builder:${TAG}_Qt${QT_VERSION}
    volumes:
      - ../:/home/builder/sources:ro
      - builds:/home/builder/builds
    entrypoint: /bin/bash ./gen_cmake.sh -o ../builds/${BUILD_FOLDER}

  # Build service
  build:
    image: builder:${TAG}_Qt${QT_VERSION}
    volumes:
      - ../:/home/builder/sources:ro
      - builds:/home/builder/builds
    entrypoint: cmake --build ../builds/${BUILD_FOLDER}

  # Shell service
  shell:
    image: builder:${TAG}_Qt${QT_VERSION}
    volumes:
      - ../:/home/builder/sources:ro
      - builds:/home/builder/builds
    entrypoint: /bin/bash

  # Run service
  run:
    image: builder:${TAG}_Qt${QT_VERSION}
    volumes:
      - builds:/home/builder/builds
    entrypoint: ./${APP}
    working_dir: /home/builder/builds/${BUILD_FOLDER}/Install/bin
